module.exports = {
  rules: {
    'body-max-length': [0],
    'scope-case': [0, 'never', 'start-case'],
    'subject-full-stop': [2, 'always', '.'],
    'subject-case': [2, 'always', 'sentence-case'],
    'type-enum': [
      2,
      'always',
      [
        'type',
        'tests',
        'break',
        'breaking',
        'release',
        'new',
        'update',
        'feature',
        'fix',
        'deps',
        'docs',
        'revert',
        'style',
        'security',
        'types',
        'misc',
        'ci',
        'build',
        'test',
        'internal',
      ],
    ],
  },
};
